#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2017
pull_requests:  
  do_not_increment_build_number: true
nuget:  
  disable_publish_on_pr: true
test: off  
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
dotnet_csproj:
  patch: true
  file: '.\src\**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Hexiron.AspNetCore.Authentication.AzureAdMixed.sln
build_script:
  - cmd: dotnet build ./Hexiron.AspNetCore.Authentication.AzureAdMixed.sln
after_build:
  - cmd: dotnet pack ./src/Hexiron.AspNetCore.Authentication.AzureAdMixed/Hexiron.AspNetCore.Authentication.AzureAdMixed.csproj
artifacts:
 - path: '**\*.nupkg'
test_script:
  # run the unit tests (requires changing into the test directory)
  #- cmd: cd tests
  #- cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy:
  provider: NuGet
  api_key:
    secure: gSsRi67VKE/odA2UP7XTEjIbuD/Q6rclh6sucrB4DBZnEvkA5BtexBxrYNRju3Rq
  skip_symbols: false
  artifact: /.*\.nupkg/
 # on:
 #     branch: master                # release from master branch only
 #     appveyor_repo_tag: true       # deploy on tag push only