#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2017

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Hexiron.AspNetCore.Authentication.AzureAdMixed.sln --verbosity d
build_script:
  - cmd: dotnet build ./Hexiron.AspNetCore.Authentication.AzureAdMixed.sln --verbosity d
after_build:
  # For once the build has completed
artifacts:

test_script:
  # run the unit tests (requires changing into the test directory)
  #- cmd: cd tests
  #- cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off