#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2017
pull_requests:  
  do_not_increment_build_number: true
nuget:  
  disable_publish_on_pr: true
test: off  
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
  - ps: if ( ($env:APPVEYOR_REPO_BRANCH -eq 'master') -and ($env:APPVEYOR_REPO_TAG -eq $TRUE) ) { $env:APPVEYOR_BUILD_VERSION = $env:APPVEYOR_REPO_TAG_NAME }
install:
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Hexiron.AspNetCore.Authentication.AzureAdMixed.sln
build_script:
- ps: .\build.ps1 $env:APPVEYOR_BUILD_VERSION $env:APPVEYOR_REPO_TAG_NAME
after_build:
  - cmd: dotnet pack ./src/Hexiron.AspNetCore.Authentication.AzureAdMixed/Hexiron.AspNetCore.Authentication.AzureAdMixed.csproj
artifacts:
 - path: '**\*.nupkg'
test_script:
  # run the unit tests (requires changing into the test directory)
  #- cmd: cd tests
  #- cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy:
  provider: NuGet
  api_key:
    secure: gSsRi67VKE/odA2UP7XTEjIbuD/Q6rclh6sucrB4DBZnEvkA5BtexBxrYNRju3Rq
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true